apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: nginx-deployment
spec:
  replicas: 2 # tells deployment to run 2 pods matching the template
  template: # create pods using pod definition in this template
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: quay.io/whisk/air-nginx:v0.0.1
        ports:
        - containerPort: 80
        livenessProbe:
          # an http probe
          httpGet:
            path: /_status/healthz
            port: 80
          # length of time to wait for a pod to initialize
          # after pod startup, before applying health checking
          initialDelaySeconds: 15
          timeoutSeconds: 1
      imagePullSecrets:
      - name: air-key